### ISSUE TITLE
Popups are blank

### ISSUE THREAD

**Issue by vhemery** [hupf/tabmarks#14]
When clicking on a popup link ( with address "javascript:void(0);"), the opened popup is always blank and the target URL does not appear in the address bar.

When I deactivate the extension, popups are back (no need to even reload the origin page).

This looks quite like this question, so probably other extensions had the same issue :
https://support.mozilla.org/fr/questions/981169

**Comment by hupf** [comment]
Thank you for reporting this. Indeed, the problem lies here:
https://github.com/hupf/tabmarks/blob/master/src/background/main.js#L72

What the extension does:
* If the browser is configured to open the tabs from the last session, it only activates the previously selected group in the menu (all tabs of the group are already open).
* Otherwise the group's tabs are opened by the extension.

If a window is created, and it already has tabs, I assume it's the first case. But for the second case it's not that easy. These "popups" that are created with `window.open` are just normal windows (with type "normal", except they have no tab- and toolbar). I don't know how to differenciate them from newly opened windows with the currently available WebExtension API…

I'm thinking about to require users to enable the «Show your windows and tabs from last time» option (and communicate this via notification after installation), since this is also the most performant way to open the tabs. The extension then only activates the group in the menu.

What do you think? Any other ideas?

BTW I've found a good resource with example popup links:
http://alistapart.com/d/popuplinks/examples.html

**Comment by ogasser** [comment]
That sounds like an approach worth trying to me!

More comments/ideas:

* Does that mean that these popups dont have the [type](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/windows/WindowType) set to `popup`? Shouldnt they have that set?
* Can we use the [openerTabId](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/Tab) property to distinguish between tabs opened on browser launch and popups?
* Should popup windows always have exactly 1 tab? If so that could be another discriminator.

**Comment by ogasser** [comment]
@hupf Are you still working on that issue? It's quite vital as day to day browsing is not really doable without popups for me.

**Comment by hupf** [comment]
> Does that mean that these popups dont have the type set to popup? Shouldnt they have that set?

Yes, they have the type `normal`. It's not clear to me which windows will have the type `popup`.

> Can we use the openerTabId property to distinguish between tabs opened on browser launch and popups?

I don't think so. The tab in these "popups" does not have any `openerTabId` set. Neither do restored tabs.

> Should popup windows always have exactly 1 tab? If so that could be another discriminator.

Unfortunately this isn't a distinguishable property (any new window you open has usually 1 tab).

I'm not so happy about the notification idea. Maybe it would be easier to make use of `sessions.setTabValue()` and `sessions.getTabValue()` to _mark_ tabs by setting some value. I suppose restored tabs should then have that value set... I haven't got time to try this.

**Comment by hupf** [comment]
I think I was able to fix the issue, please try out version 1.0.0beta4 once it will be reviewed and published.

**Comment by ogasser** [comment]
After first tests I found it to be working well now 👍

**Comment by vhemery** [comment]
Same observations here.
By the way, this also fixed an issue I discovered recently on the layout of a dokuwiki page
(page content was moved down after the table of content, instead of on the right, and a "Go to content" link was displayed on top of the page)
So I guess the two issues were tightly related and this new version fixes it all.
Thank you for the nice job.
